server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true